--------------------------------------------------------
-- Archivo creado  - domingo-abril-24-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence INCREMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "ROOM_MANAGER"."INCREMENTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTO2
--------------------------------------------------------

   CREATE SEQUENCE  "ROOM_MANAGER"."INCREMENTO2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ELEMENTOS
--------------------------------------------------------

  CREATE TABLE "ROOM_MANAGER"."ELEMENTOS" 
   (	"PK_ID_ELEMENTO" NUMBER(*,0), 
	"NOMBRE_ELEMENTO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVAS
--------------------------------------------------------

  CREATE TABLE "ROOM_MANAGER"."RESERVAS" 
   (	"PK_ID_RESERVA" NUMBER(*,0), 
	"NOMBRE_EVENTO_RESERVA" VARCHAR2(100 BYTE), 
	"FECHA_HORA_INICIO_RESERVA" TIMESTAMP (6), 
	"FECHA_HORA_FIN_RESERVA" TIMESTAMP (6), 
	"FK_ID_SALA" NUMBER(*,0), 
	"FK_ID_USUARIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "ROOM_MANAGER"."ROLES" 
   (	"ID_ROL" NUMBER(*,0), 
	"NOMBRE_ROL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SALAS
--------------------------------------------------------

  CREATE TABLE "ROOM_MANAGER"."SALAS" 
   (	"PK_ID_SALA" NUMBER(*,0), 
	"NOMBRE_SALA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SALAS_ELEMENTOS
--------------------------------------------------------

  CREATE TABLE "ROOM_MANAGER"."SALAS_ELEMENTOS" 
   (	"PK_ID_SALAS_ELEMENTOS" NUMBER(*,0), 
	"FK_ID_SALA" NUMBER(*,0), 
	"FK_ID_ELEMENTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "ROOM_MANAGER"."USUARIOS" 
   (	"PK_ID_USUARIO" NUMBER(*,0), 
	"NOMBRE_USUARIO" VARCHAR2(20 BYTE), 
	"IDENTIFICACION_USUARIO" CHAR(10 BYTE), 
	"CONTRASEÑA_USUARIO" CHAR(8 BYTE), 
	"FK_ID_ROL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ROOM_MANAGER.ELEMENTOS
SET DEFINE OFF;
REM INSERTING into ROOM_MANAGER.RESERVAS
SET DEFINE OFF;
REM INSERTING into ROOM_MANAGER.ROLES
SET DEFINE OFF;
REM INSERTING into ROOM_MANAGER.SALAS
SET DEFINE OFF;
REM INSERTING into ROOM_MANAGER.SALAS_ELEMENTOS
SET DEFINE OFF;
REM INSERTING into ROOM_MANAGER.USUARIOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Trigger TRG_ELEMENTOS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOM_MANAGER"."TRG_ELEMENTOS" 
before insert on elementos 
for each row
begin 
        select incremento.nextval into :new.pk_id_elemento from dual;
        end;
/
ALTER TRIGGER "ROOM_MANAGER"."TRG_ELEMENTOS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RESERVAS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOM_MANAGER"."TRG_RESERVAS" 
before insert on reservas
for each row
begin 
        select incremento.nextval into :new.pk_id_reserva from dual;
        end;
/
ALTER TRIGGER "ROOM_MANAGER"."TRG_RESERVAS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ROLES
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOM_MANAGER"."TRG_ROLES" 
before insert on roles 
for each row
begin 
        select incremento.nextval into :new.id_rol from dual;
        end;
/
ALTER TRIGGER "ROOM_MANAGER"."TRG_ROLES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_SALAS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOM_MANAGER"."TRG_SALAS" 
before insert on salas
for each row
begin 
        select incremento.nextval into :new.pk_id_sala from dual;
        end;
/
ALTER TRIGGER "ROOM_MANAGER"."TRG_SALAS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_USUARIOS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOM_MANAGER"."TRG_USUARIOS" 
before insert on usuarios
for each row
begin 
        select incremento.nextval into :new.pk_id_usuario from dual;
        end;
/
ALTER TRIGGER "ROOM_MANAGER"."TRG_USUARIOS" ENABLE;
--------------------------------------------------------
--  Constraints for Table ELEMENTOS
--------------------------------------------------------

  ALTER TABLE "ROOM_MANAGER"."ELEMENTOS" ADD PRIMARY KEY ("PK_ID_ELEMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOM_MANAGER"."ELEMENTOS" MODIFY ("NOMBRE_ELEMENTO" NOT NULL ENABLE);
  ALTER TABLE "ROOM_MANAGER"."ELEMENTOS" MODIFY ("PK_ID_ELEMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALAS
--------------------------------------------------------

  ALTER TABLE "ROOM_MANAGER"."SALAS" ADD PRIMARY KEY ("PK_ID_SALA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOM_MANAGER"."SALAS" MODIFY ("NOMBRE_SALA" NOT NULL ENABLE);
  ALTER TABLE "ROOM_MANAGER"."SALAS" MODIFY ("PK_ID_SALA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "ROOM_MANAGER"."USUARIOS" ADD PRIMARY KEY ("PK_ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOM_MANAGER"."USUARIOS" MODIFY ("FK_ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "ROOM_MANAGER"."USUARIOS" MODIFY ("CONTRASEÑA_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ROOM_MANAGER"."USUARIOS" MODIFY ("IDENTIFICACION_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ROOM_MANAGER"."USUARIOS" MODIFY ("NOMBRE_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ROOM_MANAGER"."USUARIOS" MODIFY ("PK_ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "ROOM_MANAGER"."ROLES" ADD PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOM_MANAGER"."ROLES" MODIFY ("NOMBRE_ROL" NOT NULL ENABLE);
  ALTER TABLE "ROOM_MANAGER"."ROLES" MODIFY ("ID_ROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVAS
--------------------------------------------------------

  ALTER TABLE "ROOM_MANAGER"."RESERVAS" ADD PRIMARY KEY ("PK_ID_RESERVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOM_MANAGER"."RESERVAS" MODIFY ("FK_ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ROOM_MANAGER"."RESERVAS" MODIFY ("FK_ID_SALA" NOT NULL ENABLE);
  ALTER TABLE "ROOM_MANAGER"."RESERVAS" MODIFY ("FECHA_HORA_FIN_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "ROOM_MANAGER"."RESERVAS" MODIFY ("FECHA_HORA_INICIO_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "ROOM_MANAGER"."RESERVAS" MODIFY ("NOMBRE_EVENTO_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "ROOM_MANAGER"."RESERVAS" MODIFY ("PK_ID_RESERVA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALAS_ELEMENTOS
--------------------------------------------------------

  ALTER TABLE "ROOM_MANAGER"."SALAS_ELEMENTOS" ADD PRIMARY KEY ("PK_ID_SALAS_ELEMENTOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOM_MANAGER"."SALAS_ELEMENTOS" MODIFY ("FK_ID_ELEMENTO" NOT NULL ENABLE);
  ALTER TABLE "ROOM_MANAGER"."SALAS_ELEMENTOS" MODIFY ("FK_ID_SALA" NOT NULL ENABLE);
  ALTER TABLE "ROOM_MANAGER"."SALAS_ELEMENTOS" MODIFY ("PK_ID_SALAS_ELEMENTOS" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table RESERVAS
--------------------------------------------------------

  ALTER TABLE "ROOM_MANAGER"."RESERVAS" ADD CONSTRAINT "FK_ID_SALA2" FOREIGN KEY ("FK_ID_SALA")
	  REFERENCES "ROOM_MANAGER"."SALAS" ("PK_ID_SALA") ENABLE;
  ALTER TABLE "ROOM_MANAGER"."RESERVAS" ADD CONSTRAINT "FK_ID_USUARIO" FOREIGN KEY ("FK_ID_USUARIO")
	  REFERENCES "ROOM_MANAGER"."USUARIOS" ("PK_ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALAS_ELEMENTOS
--------------------------------------------------------

  ALTER TABLE "ROOM_MANAGER"."SALAS_ELEMENTOS" ADD CONSTRAINT "FK_ID_ELEMENTO" FOREIGN KEY ("FK_ID_ELEMENTO")
	  REFERENCES "ROOM_MANAGER"."ELEMENTOS" ("PK_ID_ELEMENTO") ENABLE;
  ALTER TABLE "ROOM_MANAGER"."SALAS_ELEMENTOS" ADD CONSTRAINT "FK_ID_SALA" FOREIGN KEY ("FK_ID_SALA")
	  REFERENCES "ROOM_MANAGER"."SALAS" ("PK_ID_SALA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "ROOM_MANAGER"."USUARIOS" ADD CONSTRAINT "FK_ID_ROL" FOREIGN KEY ("FK_ID_ROL")
	  REFERENCES "ROOM_MANAGER"."ROLES" ("ID_ROL") ENABLE;
